# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenthostel',
            name='gender',
        ),
        migrations.AddField(
            model_name='currenthostel',
            name='bufferSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='bufferSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='genderType',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offlineprofile',
            name='techProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reg.TechProfile'),
        ),
    ]
