# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170212_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthostel',
            name='hostel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.Hostel'),
        ),
    ]
