# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170212_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='crediter',
            new_name='creditor',
        ),
    ]
