# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170212_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
